2020-09-03T11:26:24|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\OPT\anaconda3\envs\ScopeFoundry\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\OPT\anaconda3\envs\ScopeFoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "D:\LabPrograms\ScopeFoundry_POLIMI\DMD_ScopeFoundry\DMDHardware.py", line 55, in connect
    self.dmd = DmdDeviceHID()
  File "D:\LabPrograms\ScopeFoundry_POLIMI\DMD_ScopeFoundry\DMDDeviceHID.py", line 33, in __init__
    self.device = hid.device()
AttributeError: module 'hid' has no attribute 'device'

